project:
  type: book
date: today
date-format: "long"
version: "1.0.0"

book:
  title: "A Quarto book project for Tufte-style layout"
  author: "Neel Smith"

  page-footer:
    left: "© 2026 Neel Smith"
    right: "Version **{{< meta version >}}**,  {{< meta date >}}"
    
  chapters:
    - releases.qmd
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib
link-citations: true 

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    page-layout: article
    
  pdf:
    toc: true
    pdf-engine: xelatex
    fontsize: 11pt
    number-sections: true
    mainfont: "Georgia" 
    
    # Precise Tufte-style layout math for LaTeX
    geometry:
      - top=2.5cm
      - bottom=2.5cm
      - left=2.5cm
      - right=5cm          # Outer page boundary edge
      - marginparwidth=3.5cm  # Widens the actual container for the notes
      - marginparsep=0.5cm   # The buffer gap between body text and side notes
      
    colorlinks: true
    include-in-header:
      - text: |
          \usepackage{hyperref}
          \hypersetup{
            colorlinks=true,
            linkcolor=[rgb]{0.10,0.37,0.70},
            citecolor=[rgb]{0.10,0.37,0.70},
            urlcolor=[rgb]{0.10,0.37,0.70}
          }